### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by MartianH** [tendermint/rust-tsp#12]
Issue #10 is still open not to mention that 0.21 is the current version.

**Comment by xla** [comment]
@adrianbrink Can you follow-up?

**Comment by JacksonCoder** [comment]
In case anyone is interested, I've updated this library to be compliant with Tendermint 0.22, on my own fork. I'll probably make a pull request soon. Here's the link to the fork: http://github.com/jacksoncoder/rust-tsp

**Comment by JacksonCoder** [comment]
Alright, should we close this?

**Comment by ValarDragon** [comment]
Yup, thanks for updating this! Great job :)
