### ISSUE TITLE
Create a 'counter' example

### ISSUE THREAD

**Issue by JacksonCoder** [tendermint/rust-tsp#14]
One thing a library never can have too many of is examples! Right now, our only example is a bare-bones implementation of an `Application`. Now that #13 is merged, we'll actually be able to create a mutable-state application as an example. A 'counter' application would probably be a good and simple example of an ABCI app, so I was thinking that would be a good example to add to the library. I know we had one before, but that one didn't actually function as a counter app.

**Comment by melekes** [comment]
Counter app was added in #18 🕺
